// swift-tools-version:5.9
import PackageDescription

// AmberHTML Swift package.
//
// The native code ships as a binary xcframework (`AmberCoreFFI.xcframework`)
// built by `build-xcframework.sh`; the Swift wrapper in Sources/AmberHTML is
// generated by `generate.sh`. Both run before `swift build`. Released versions
// attach a zipped xcframework + checksum to the GitHub Release and switch the
// binaryTarget to a `url:`/`checksum:` form.
let package = Package(
    name: "AmberHTML",
    platforms: [.macOS(.v11)],
    products: [
        .library(name: "AmberHTML", targets: ["AmberHTML"])
    ],
    targets: [
        // The UniFFI C shim (header + modulemap), packaged as a binary target.
        .binaryTarget(name: "amber_coreFFI", path: "AmberCoreFFI.xcframework"),
        // The generated Swift wrapper.
        .target(
            name: "AmberHTML",
            dependencies: ["amber_coreFFI"],
            path: "Sources/AmberHTML"
        ),
        .testTarget(
            name: "AmberHTMLTests",
            dependencies: ["AmberHTML"],
            path: "Tests/AmberHTMLTests"
        ),
    ]
)
